
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module exp09movimg(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================

//clkgen #(25000000) my_vgaclk(CLOCK_50,SW[0],1'b1,VGA_CLK);
//top_flyinglogo(clk, rst, hsync, vsync, vga_r, vga_g, vga_b);
top_flyinglogo logo1(CLOCK_50, SW[1], VGA_HS, VGA_VS, VGA_R[7:4], VGA_G[7:4], VGA_B[7:4], VGA_CLK, VGA_BLANK_N);


endmodule
