
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module LFSR8(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// Seg7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================

assign LEDR[8] = 0;
assign HEX2 = 7'b1111111;
assign HEX3 = 7'b1111111;
assign HEX4 = 7'b1111111;
assign HEX5 = 7'b1111111;
clock_1 myclk(CLOCK_50, LEDR[9]);
RanGen rg(LEDR[9], SW[9], SW[8], SW[7:0], LEDR[7:0]);
//RanGen rg(CLOCK_50, SW[9], SW[8], SW[7:0], LEDR[7:0]);
hex15 hex1(LEDR[3:0], HEX0);
hex15 hex2(LEDR[7:4], HEX1);
endmodule
