
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module exp09staticimg(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS
);


//=======================================================
//  REG/WIRE declarations
//=======================================================



//=======================================================
//  Structural coding
//=======================================================

clkgen #(25000000) my_vgaclk(CLOCK_50,SW[0],1'b1,VGA_CLK);
//vga_ctrl(pclk,reset,vga_data,[9:0] h_addr,[9:0] v_addr,hsync,vsync,valid,[7:0] vga_r,[7:0] vga_g,[7:0] vga_b);

//picture(clk,reset,VGA_BLANK_N,[7:0]VGA_R,[7:0]VGA_B,[7:0]VGA_G,VGA_HS,VGA_SYNC_N,VGA_VS);
picture p1(VGA_CLK, 1'b0, VGA_BLANK_N, VGA_R, VGA_B, VGA_G, VGA_HS, VGA_SYNC_N, VGA_VS);
endmodule
