
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module ex_4_1(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SW //////////
	input 		     [1:0]		SW,

	//////////// LED //////////
	output		     [3:0]		LEDR
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

nonblocing_assign test1(SW[1], CLOCK_50, SW[0], LEDR[0], LEDR[1]);
blocing_assign test2(SW[1], CLOCK_50, SW[0], LEDR[2], LEDR[3]);


//=======================================================
//  Structural coding
//=======================================================



endmodule
